# Generated by Django 2.2.5 on 2019-09-16 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benchmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'branches',
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('unit', models.CharField(default='seconds', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42, unique=True)),
                ('default_branch', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commitid', models.CharField(max_length=42)),
                ('tag', models.CharField(blank=True, max_length=64, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('title', models.CharField(blank=True, max_length=64)),
                ('message', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='perfdata.Branch')),
            ],
            options={
                'unique_together': {('commitid', 'branch')},
            },
        ),
        migrations.CreateModel(
            name='Executable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executables', to='perfdata.Repo')),
            ],
            options={
                'unique_together': {('name', 'repo')},
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='perfdata.Repo'),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('benchmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='perfdata.Benchmark')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='perfdata.Environment')),
                ('executable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='perfdata.Executable')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='perfdata.Metric')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='perfdata.Revision')),
            ],
            options={
                'unique_together': {('revision', 'executable', 'benchmark', 'metric', 'environment')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('name', 'repo')},
        ),
    ]
